sudo: false

dist: xenial

language: java

jdk:
  - openjdk8

notifications:
  slack:
    if: branch = master
    on_success: change
    on_failure: always
    rooms:
      - secure: "Q4/OstLjR1pBpBgrMWBQF/XckuWp+tQvqNbSGDuckDOV/h9QN59ergZFwR0vt/pJdLii0XG9g4frH1BsDy0RYq/NrS+0bsnXEkYJqIGngd9szoM/+CnW6DVfu8xbSPsEOZ33TysxZBeMQZJEJEkKab1ELHAl/TDloNIw94VMC/M="
