FROM alpine:3.20
RUN apk add --no-cache fasttext openjdk21-jre

RUN adduser -u 10000 -h /home/languagetool -D languagetool
USER languagetool

WORKDIR /home/languageTool

COPY libs/ libs
COPY META-INF/ META-INF
COPY org/ org
COPY languagetool-server.jar .
COPY lid.176.bin .
COPY server.properties .

EXPOSE 8181/tcp

ENTRYPOINT [ "java", "-cp", "languagetool-server.jar", "org.languagetool.server.HTTPServer", "--config", "server.properties", "--port", "8181", "--allow-origin", "--public" ]
