BEGIN {IGNORECASE=1}
!/^(abdominal N:|aberrant N:|abnormal N:|absurd N:|acoustic N:|\
actual N:|after N|acupuncture V:|adipose N:|adulterate A:|adz V:|\
adze V:|aesthetic N:|afar N:|afferent N:|affiance N:|affluent N:|\
affray V:|aforethought N:|ageing N:|agent V:|airfreight V:|alligator V:|\
allover N:|allowance V:|alpha A:|altogether N:|aluminum A:|ambient N:|\
ambition V:|amen N:|amok N:|amuck N:|anagram V:|angel V:|anneal N:|\
antedate N:|antediluvian N:|anthem V:|antiaircraft N:|antidote V:|\
antimalarial N:|antimicrobial N:|antimissile N:|antislavery N:|apical N:|\
apoplectic N:|appurtenant N:|apron V:|arable N:|arbitrary N:|arcade V:|\
architect V:|armorial N:|arrow V:|arterial N:|article V:|aseptic N:|ashlar V:|\
aspen A:|asphalt A:|asteroid A:|astigmatic N:|auctioneer V:|audiovisual N:|\
auditory N:|augment N:|augmentative N:|auricular N:|austral N:|autoclave V:|\
avalanche V:|awol N:|backdrop V:|backgammon V:|background V:|backlash V:|\
backwash V:|badge V:|badinage V:|bagpipe V:|bailout A:|baize V:|baksheesh V:|\
bandy N:|bard V:|barn V:|basset V:|baste N:|bate N:|bath V:|batik V:|\
battledore V:|bawdy N:|beacon V:|beau V:|beck V:|beckon N:|beeswax V:|\
beg N:|begum V:|belay N:|benchmark V:|benefice V:|berserk N:|between N:|\
bib V:|big V:|bight V:|bilge V:|bilk N:|billboard V:|biologic N:|biological N:|\
birdlime V:|bishop V:|bit V:|bitter V:|bivalent N:|blabber N:|blackbird V:|\
blackguard V:|bleak N:|blear V:|bleed N:|blinding N:|blip V:|blitzkrieg V:|\
bloat N:|blubber A:|blurb V:|bobtail A:|bobtail V:|body V:|boldface V:|\
bolt A:|bombard N:|bond A:|bone A:|bonnet V:|bonnie N:|bonny N:|\
boodle V:|boring N:|bosom V:|bossy N:|botanical N:|bottleneck V:|\
bowel V:|bower V:|bowstring V:|bracing N:|brad V:|brag A:|braille V:|\
bramble V:|bran V:|brander V:|brandish N:|brash N:|brassy N:|bravo V:|\
breadboard V:|bream V:|breech V:|brigade V:|brine V:|briny N:|briquet V:|\
briquette V:|brittle V:|broom V:|bruit N:|brute V:|buckler V:|buckram V:|\
buddy A:|buddy V:|budge N:|bullet V:|bulwark V:|bumble N:|bumper V:|\
bung A:|bunker V:|bunko V:|bur V:|burgeon N:|burl V:|but A:|burning N:|\
bush A:|byline V:|cabal V:|cabbage V:|cabin V:|cadence V:|cadge N:|\
cakewalk V:|caller A:|callow N:|caloric N:|cam V:|came N:|canal V:|\
canary A:|cancel N:|candid N:|candidate V:|cannonball A:|cant A:|\
canton V:|cape V:|car A:|caravan V:|carcass V:|\
cardiac N:|\
careen N:|\
carhop V:|\
carny A:|\
carny V:|\
carton V:|\
cask V:|\
casket V:|\
castrate N:|\
cat V:|\
catchpenny N:|\
cathedral A:|\
catty N:|\
causative N:|\
causeway V:|\
cavalier V:|\
cavern V:|\
celestial N:|\
cellar V:|\
centrifugal N:|\
cerebral N:|\
chafe N:|\
chairman V:|\
chamber V:|\
chammy V:|\
chamois V:|\
chapel V:|\
chapter V:|\
character V:|\
charcoal V:|\
chariot V:|\
chartreuse A:|\
cheap N:|\
checkerboard V:|\
chicane V:|\
chimney V:|\
chine V:|\
chipper V:|\
choir V:|\
chord V:|\
choroid A:|\
chose N:|\
chump V:|\
chunk V:|\
church V:|\
chute V:|\
cincture V:|\
circumflex A:|\
circumflex V:|\
clad V:|\
clangor V:|\
clangour V:|\
clay V:|\
cleat V:|\
clerical N:|\
clinker V:|\
clique V:|\
closure V:|\
cloture V:|\
cnidarian A:|\
coagulate A:|\
cobweb V:|\
cockfighting A:|\
cockle V:|\
cocktail V:|\
cocky N:|\
coelenterate A:|\
coffeehouse V:|\
coffer V:|\
cog V:|\
collage V:|\
collegiate N:|\
colloid A:|\
columbine A:|\
commemorative N:|\
commie A:|\
communicant A:|\
companion V:|\
company V:|\
compartment V:|\
compassion V:|\
compassionate V:|\
compeer V:|\
complementary N:|\
complex V:|\
complicate A:|\
composite V:|\
compulsive N:|\
compute N:|\
concave V:|\
conceit V:|\
concessionary N:|\
concurrent N:|\
cone V:|\
confection V:|\
conference V:|\
confident N:|\
confiscate A:|\
confluent N:|\
congregate A:|\
congress V:|\
conjugate N:|\
consecrate A:|\
consequent N:|\
conservatory A:|\
considerable N:|\
constabulary A:|\
construe N:|\
contaminate A:|\
contradictory N:|\
contralto A:|\
contributory N:|\
convict A:|\
copper V:|\
corbel V:|\
corduroy V:|\
cornice V:|\
corroborate A:|\
corrugate A:|\
cosset N:|\
cosy V:|\
cote V:|\
cotter V:|\
counterpoint V:|\
counterweight V:|\
coup V:|\
courtesy V:|\
cove V:|\
cowhide V:|\
cowl V:|\
coy V:|\
cozy V:|\
cram N:|\
crape V:|\
craven V:|\
crawfish V:|\
credential A:|\
credential V:|\
crenelate A:|\
crenellate A:|\
crepe V:|\
crescendo V:|\
crevasse V:|\
cricket V:|\
crock V:|\
croquet V:|\
crossbred N:|\
crosshatch N:|\
crosstown N:|\
crowbar V:|\
crowning N:|\
crud V:|\
crummy N:|\
crutch V:|\
crystal V:|\
cub V:|\
cubic N:|\
cuckoo V:|\
cumber N:|\
curd V:|\
custodial N:|\
customary N:|\
cyanide V:|\
cyclical N:|\
cylinder V:|\
cynic A:|\
dado V:|\
dagger V:|\
damndest N:|\
damnedest N:|\
dangle N:|\
dark V:|\
dastard A:|\
daylight V:|\
deacon V:|\
deafening N:|\
deal A:|\
debouch N:|\
decal V:|\
decision V:|\
dedicate A:|\
defence V:|\
defendant A:|\
deficient N:|\
definitive N:|\
defoliate A:|\
deject A:|\
delectable N:|\
delicate N:|\
demagog V:|\
demagogue V:|\
demolition A:|\
demoniac N:|\
demotic N:|\
den V:|\
denizen V:|\
dental N:|\
deponent A:|\
derail N:|\
derogate A:|\
derrick V:|\
descant A:|\
desiccant A:|\
desirable N:|\
desperate N:|\
despite N:|\
despite V:|\
destitute V:|\
determinate V:|\
detrimental N:|\
dew V:|\
diadem V:|\
diagnostic N:|\
dialog V:|\
dialogue V:|\
diamond V:|\
diaphragm V:|\
dick V:|\
dicker N:|\
dickey A:|\
difference V:|\
digestive N:|\
digital N:|\
dike V:|\
dimension V:|\
dingdong A:|\
dint V:|\
diphthong V:|\
diploma V:|\
directory A:|\
dirigible A:|\
dirk V:|\
disagreeable N:|\
disc V:|\
disciple V:|\
discomfit N:|\
discountenance N:|\
discriminate A:|\
disease V:|\
disinterest V:|\
disjoint A:|\
disjunctive N:|\
disk V:|\
dismal N:|\
disperse A:|\
displeasure V:|\
disport N:|\
dispose N:|\
disproportion V:|\
disquiet A:|\
dissolve N:|\
distaste V:|\
distemper V:|\
distributive N:|\
district V:|\
ditty V:|\
diurnal N:|\
dolly V:|\
douse N:|\
downcast N:|\
downstage N:|\
dowse N:|\
dozen V:|\
drab V:|\
dram V:|\
drat V:|\
dray V:|\
dreadful N:|\
drench N:|\
drinkable N:|\
droll V:|\
drove V:|\
drub N:|\
druggie A:|\
druggy A:|\
dual N:|\
duct V:|\
duet V:|\
duff V:|\
dug N:|\
dulcet N:|\
dummy V:|\
duodecimal N:|\
duplex V:|\
durable N:|\
dusk A:|\
dusk V:|\
dwell N:|\
dyke V:|\
eager N:|\
eagle V:|\
ear V:|\
early N:|\
earwig V:|\
eastward N:|\
echelon V:|\
ecstatic N:|\
effective N:|\
effeminate V:|\
efferent N:|\
effuse A:|\
eggshell A:|\
egress V:|\
ejaculate N:|\
elderly N:|\
electric N:|\
electroplate N:|\
electroshock V:|\
electrotype V:|\
elemental N:|\
elevated N:|\
elfin N:|\
eligible N:|\
elliptical N:|\
elongate A:|\
emasculate A:|\
emblem V:|\
embryo A:|\
emergency A:|\
emergent N:|\
emerita N:|\
emeritus N:|\
emphatic N:|\
empiric N:|\
enclave V:|\
enervate A:|\
ensilage V:|\
entail N:|\
entire N:|\
ephemera N|\
ephemeral N:|\
epitaph V:|\
equatorial N:|\
equinoctial N:|\
equipoise V:|\
erotic N:|\
eruptive N:|\
escrow V:|\
esquire V:|\
estate V:|\
esthetic N:|\
eternal N:|\
ethylene A:|\
eviscerate A:|\
ex A:|\
exasperate A:|\
excess V:|\
excommunicate A:|\
excommunicate N:|\
excursion V:|\
exempt N:|\
existent N:|\
expectant N:|\
expedite A:|\
expense V:|\
expert V:|\
expertise V:|\
expletive A:|\
exponential N:|\
exquisite N:|\
extravert A:|\
extravert V:|\
extrovert V:|\
eyelet V:|\
fable V:|\
facelift V:|\
faerie A:|\
faery A:|\
fair V:|\
fame V:|\
fang V:|\
fantastic N:|\
farce V:|\
farrow A:|\
fashionable N:|\
fat V:|\
fatigue A:|\
feat A:|\
fee V:|\
fellow V:|\
fellowship V:|\
felon A:|\
ferrule V:|\
ferule V:|\
fess N:|\
fetch N:|\
fettle V:|\
fever V:|\
fiberglass V:|\
fibroid N:|\
fife V:|\
filthy V:|\
fin V:|\
financier V:|\
finite N:|\
fishtail N:|\
fission V:|\
fissionable N:|\
fissure V:|\
fist V:|\
flack V:|\
flagellate N:|\
flagging N:|\
flamboyant N:|\
flange V:|\
flew N:|\
flight V:|\
flimsy N:|\
flint V:|\
floral N:|\
flume V:|\
fluorescent N:|\
fluoroscope V:|\
fodder V:|\
foldaway N:|\
folio A:|\
folio V:|\
follow N:|\
fond N:|\
fondu A:|\
football V:|\
forelock V:|\
forklift V:|\
formative N:|\
forthright N:|\
fortissimo N:|\
fortnightly N:|\
fortune V:|\
found N:|\
foursquare N:|\
fraction V:|\
frail N:|\
frappe V:|\
fraught N:|\
freewheel N:|\
frenetic N:|\
frenzy V:|\
fresco V:|\
fresh N:|\
fresh V:|\
freshman A:|\
friend V:|\
frill V:|\
frisk N:|\
fro N:|\
frock V:|\
frog V:|\
frolic A:|\
frontal N:|\
frosted N:|\
frustrate A:|\
fucking N:|\
fugue V:|\
fulcrum V:|\
fuller V:|\
fulminate N:|\
fun V:|\
functional N:|\
fungoid N:|\
furbelow V:|\
furnace V:|\
fusillade V:|\
gad N:|\
gaggle V:|\
gait V:|\
gallant V:|\
gammon V:|\
gander V:|\
gantlet V:|\
gap V:|\
gar V:|\
garble N:|\
garment V:|\
garner N:|\
garter V:|\
gash A:|\
gaudy N:|\
gauntlet V:|\
gavel V:|\
gavotte V:|\
gawk N:|\
gee N:|\
geld N:|\
gem V:|\
gender V:|\
gentle N:|\
geometric N:|\
geriatric N:|\
ghetto V:|\
gibber N:|\
giddy V:|\
gill V:|\
gimmick V:|\
ginger V:|\
gipsy V:|\
gird N:|\
girly N:|\
girth V:|\
glad V:|\
glassy N:|\
glee V:|\
glister N:|\
glitz V:|\
globe V:|\
gloom V:|\
gnawing N:|\
god V:|\
goddamn V:|\
godfather V:|\
gopher V:|\
gormandize N:|\
gospel V:|\
governess V:|\
gradient A:|\
gradual N:|\
grain V:|\
gravel A:|\
griddle V:|\
gridiron V:|\
groin V:|\
grommet V:|\
grouse A:|\
grubby N:|\
grubstake V:|\
grueling N:|\
gruelling N:|\
grump V:|\
guise V:|\
gulf V:|\
gullet V:|\
gully V:|\
gurgling N:|\
guts V:|\
gypsy A:|\
gypsy V:|\
gyrate A:|\
habit V:|\
hackle V:|\
haft V:|\
haggard N:|\
halcyon N:|\
halftone A:|\
hallo V:|\
handset V:|\
hangar V:|\
hangdog N:|\
hank V:|\
hap V:|\
haphazard N:|\
harbinger V:|\
hard N:|\
hardcore N:|\
hardy N:|\
hasp V:|\
hatchet V:|\
haunting N:|\
haven V:|\
havoc V:|\
haywire N:|\
heather A:|\
heir V:|\
hello V:|\
helm V:|\
helve V:|\
herbal N:|\
heroic N:|\
hi A:|\
highball V:|\
hill V:|\
hilltop V:|\
hilt V:|\
hippy A:|\
histrionic N:|\
hob V:|\
holograph V:|\
holy N:|\
honcho V:|\
hooky A:|\
horn V:|\
horselaugh V:|\
hosanna V:|\
hostage V:|\
hot V:|\
hovel V:|\
hover N:|\
howdy N:|\
hoyden A:|\
hub V:|\
hulk V:|\
hullo V:|\
hunky N:|\
hut V:|\
hymeneal N:|\
hymnal A:|\
hyper N:|\
hypo V:|\
illegitimate N:|\
illegitimate V:|\
illuminate N:|\
imaginary N:|\
immovable N:|\
immune N:|\
imp V:|\
implosive N:|\
impost V:|\
impotent N:|\
inane N:|\
incapable N:|\
incombustible N:|\
incoming N:|\
incorrigible N:|\
indefinable N:|\
indivisible N:|\
indulgence V:|\
industrial N:|\
inexpressible N:|\
infallible N:|\
infatuate N:|\
infect A:|\
infiltrate N:|\
infirm V:|\
inflammable N:|\
influential N:|\
ingot V:|\
ingrate A:|\
inlet V:|\
innermost N:|\
innumerate N:|\
insolent N:|\
insubordinate N:|\
insular N:|\
intaglio V:|\
interlinear N:|\
interlink N:|\
intermediate V:|\
intern A:|\
internal N:|\
interne V:|\
interplay V:|\
interstitial N:|\
interurban N:|\
interweave N:|\
intestate N:|\
intolerant N:|\
introvert V:|\
inverse V:|\
invisible N:|\
inward N:|\
iris V:|\
irony A:|\
irreconcilable N:|\
irresponsible N:|\
island V:|\
isle V:|\
isometric N:|\
isthmian N:|\
item V:|\
jack A:|\
jacket V:|\
jackrabbit V:|\
jag V:|\
japan A:|\
jargon V:|\
javelin V:|\
jeep V:|\
jerkwater N:|\
jetty A:|\
jetty V:|\
jitney V:|\
jobless N:|\
joist V:|\
journal V:|\
julienne N:|\
junketeer V:|\
jury V:|\
just V:|\
kelp V:|\
kerb V:|\
kernel V:|\
kibosh V:|\
kilt V:|\
kin A:|\
king V:|\
kit V:|\
kitten V:|\
kneel N:|\
knockdown A:|\
knoll V:|\
know N:|\
known N:|\
kosher N:|\
kraal V:|\
lachrymal N:|\
lackey V:|\
lackluster N:|\
lacklustre N:|\
lacrimal N:|\
lactate N:|\
lacteal N:|\
laden V:|\
lager V:|\
lair V:|\
lamp V:|\
landfill V:|\
landmark V:|\
lane A:|\
lantern V:|\
laryngeal N:|\
lasting N:|\
lattice V:|\
launder N:|\
laurel V:|\
law A:|\
law V:|\
lawyer V:|\
leach N:|\
leaden V:|\
leather V:|\
lech V:|\
lecher V:|\
ledge V:|\
legendary N:|\
legislative N:|\
legit N:|\
lenitive N:|\
lens V:|\
lesion V:|\
lesson V:|\
levee V:|\
lichen V:|\
lid V:|\
lifeguard V:|\
lighter V:|\
lightface A:|\
lilliputian N:|\
limb V:|\
limber N:|\
limited N:|\
lingual N:|\
lip V:|\
lit N:|\
liver V:|\
livery A:|\
loam V:|\
local V:|\
loco N:|\
loco V:|\
logistic N:|\
loll N:|\
longhand A:|\
loophole V:|\
lop N:|\
lot V:|\
lout V:|\
louver V:|\
lower N:|\
lowercase V:|\
lubber A:|\
lucky N:|\
luff N:|\
lullaby V:|\
lumbar N:|\
luminary A:|\
lunar N:|\
lurk N:|\
lush V:|\
luster V:|\
lustre V:|\
lute V:|\
macrame V:|\
macrobiotic N:|\
mad V:|\
mag V:|\
maim N:|\
main V:|\
mandamus V:|\
mandatory N:|\
maraud N:|\
margin V:|\
marl V:|\
mason V:|\
mast V:|\
masthead V:|\
matriculate N:|\
maxillary N:|\
maze V:|\
meagre N:|\
mechanical N:|\
medal V:|\
mediaeval N:|\
medial N:|\
medicine V:|\
medieval N:|\
medley A:|\
menthol A:|\
mercurial N:|\
meringue V:|\
messenger V:|\
metal V:|\
metallic N:|\
metric N:|\
metropolitan N:|\
mid N:|\
middle V:|\
middling N:|\
miff N:|\
minim A:|\
minion A:|\
missing V:|\
missive A:|\
mister V:|\
mock N:|\
modem V:|\
modular N:|\
monitory N:|\
monoclonal N:|\
monocular N:|\
monograph V:|\
montage V:|\
monument V:|\
moonwalk V:|\
moot N:|\
mordant V:|\
morph N:|\
morsel V:|\
mosaic V:|\
moss V:|\
motive V:|\
motorcade V:|\
mottle N:|\
moulder N:|\
mountebank V:|\
mud V:|\
muffle N:|\
mugger V:|\
mull N:|\
mullion V:|\
multiply A:|\
mum V:|\
mummy V:|\
murk A:|\
musky N:|\
must V|\
musty N:|\
mutual N:|\
nasty N:|\
naught A:|\
neat N:|\
necklace V:|\
negotiable N:|\
nett N:|\
nett V:|\
newsy N:|\
niche V:|\
nickel V:|\
nifty N:|\
nigger V:|\
nigh V:|\
nighttime A:|\
nocturnal N:|\
nominal N:|\
nonacademic N:|\
noncombustible N:|\
noncontributory N:|\
nondescript N:|\
noneffective N:|\
nonelectric N:|\
nonessential N:|\
nonmilitant N:|\
nonperishable N:|\
nonplus N:|\
nonresistant N:|\
nonstop N:|\
nontaxable N:|\
nonthinking N:|\
nonunion N:|\
nonvocal N:|\
noose V:|\
northeastward N:|\
northern N:|\
northward N:|\
northwestward N:|\
null V:|\
numeric N:|\
nursemaid V:|\
nutritive N:|\
oblate N:|\
oblique V:|\
obscure N:|\
observable N:|\
observant N:|\
occlusive N:|\
occult V:|\
ocher V:|\
ochre V:|\
octave A:|\
odd N:|\
off N:|\
officer V:|\
offprint V:|\
omen V:|\
omnipotent N:|\
omniscient N:|\
on N:|\
oncoming N:|\
opaque N:|\
ope A:|\
opiate V:|\
or N:|\
orb V:|\
orgasm V:|\
ornamental N:|\
ouch N:|\
ouch V:|\
ought N:|\
outcry V:|\
outspread N:|\
outward N:|\
over V:|\
overburden N:|\
overcoat V:|\
overdrive V:|\
overhand V:|\
overheat N:|\
overlord V:|\
overnight V:|\
overpass V:|\
overpraise N:|\
oversea N:|\
overshoot N:|\
overshot N:|\
oversize N:|\
overstock N:|\
oversupply N:|\
overtime V:|\
overture V:|\
overturn N:|\
overweight V:|\
owl V:|\
oyster V:|\
packet V:|\
palisade V:|\
pallet V:|\
palsy A:|\
pamphleteer V:|\
pappy A:|\
paraffin V:|\
paragon V:|\
paramount N:|\
parcel A:|\
parietal N:|\
paschal N:|\
passage V:|\
passe N:|\
pastor V:|\
pauper V:|\
pavilion V:|\
payable N:|\
payoff A:|\
peace V:|\
peach V:|\
peacock V:|\
peanut A:|\
pearly N:|\
peculiar N:|\
pedestal V:|\
peen V:|\
pellmell N:|\
penitential N:|\
penny A:|\
percipient N:|\
percolate N:|\
perk A:|\
persuasive N:|\
petrol V:|\
pharyngeal N:|\
philter V:|\
philtre V:|\
phonetic N:|\
phrenetic N:|\
picayune N:|\
pickaback N:|\
pie V:|\
piffle V:|\
pigment V:|\
pilgrimage V:|\
pill V:|\
pillar V:|\
pincer V:|\
pinnacle V:|\
pipeline V:|\
pipette V:|\
pique A:|\
pistol V:|\
pitapat V:|\
pith V:|\
plain V:|\
planetary N:|\
platy A:|\
plod N:|\
ploy V:|\
pluvial N:|\
pneumatic N:|\
poetic N:|\
poky N:|\
pollen V:|\
poltroon A:|\
pond V:|\
poniard V:|\
pontifical N:|\
pony V:|\
posit N:|\
post A:|\
postal N:|\
postcard V:|\
posthaste N:|\
potent N:|\
pour N:|\
praetorian N:|\
prank V:|\
precaution V:|\
precious N:|\
predecease N:|\
predicable N:|\
preempt N:|\
preen N:|\
preform N:|\
prelude V:|\
premature N:|\
premix N:|\
prescript A:|\
pretension V:|\
prevue V:|\
priest V:|\
prig V:|\
prim V:|\
prise N:|\
privateer V:|\
procedural N:|\
profound N:|\
prolog V:|\
prologue V:|\
prone N:|\
prong V:|\
propitiatory N:|\
proportionate V:|\
prose V:|\
protocol V:|\
prototype V:|\
proverb V:|\
provisional N:|\
provocative N:|\
prow A:|\
psalm V:|\
pshaw V:|\
pug V:|\
pumice V:|\
purple V:|\
pussyfoot N:|\
quad A:|\
quad V:|\
quadrennial N:|\
quicksilver V:|\
quill V:|\
quire V:|\
quirt V:|\
quitclaim V:|\
quoin V:|\
quotidian N:|\
qwerty N:|\
rabble V:|\
radiant N:|\
radiate A:|\
radiotelephone V:|\
rafter V:|\
ragout V:|\
raiment V:|\
rainproof V:|\
ramp V:|\
rampart V:|\
random N:|\
randy N:|\
rapture V:|\
ravening N:|\
rawhide V:|\
ray V:|\
razor V:|\
ready N:|\
real N|\
real N|\
rearguard A:|\
rearward N:|\
rebid N:|\
recalcitrant N:|\
recitative A:|\
reclaim N:|\
recommission N:|\
recontact N:|\
recoup N:|\
red V:|\
redirect A:|\
redouble N:|\
redraft N:|\
reductive N:|\
reed V:|\
reflex V:|\
refuge V:|\
regal N:|\
regale N:|\
regional N:|\
reload N:|\
remainder V:|\
remand N:|\
rematch V:|\
remit N:|\
remix N:|\
remnant A:|\
renege N:|\
renewable N:|\
renounce N:|\
reorient A:|\
repaint N:|\
repent A:|\
rephotograph N:|\
reprobate V:|\
reproductive N:|\
reptile A:|\
repurchase N:|\
resin V:|\
resistant N:|\
resonant N:|\
respite V:|\
respond N:|\
restudy N:|\
resurvey N:|\
retch N:|\
retinal N:|\
reveal N:|\
revere N:|\
reversible N:|\
revert N:|\
revoke N:|\
rhythmic N:|\
ribald N:|\
ribbon V:|\
riparian N:|\
ripsaw V:|\
roach V:|\
roam N:|\
rod V:|\
rode N:|\
rodeo V:|\
rogue V:|\
roomy N:|\
rose V:|\
rotate A:|\
roulette V:|\
rove N:|\
roving N:|\
rubber V:|\
rubric A:|\
rummy A:|\
rump A:|\
rural N:|\
rust A:|\
saber V:|\
sabre V:|\
sacramental N:|\
said N:|\
sailplane V:|\
saint V:|\
sallow N:|\
sallow V:|\
salsa V:|\
salutatory N:|\
salvo V:|\
sandal V:|\
sanguine N:|\
sanitarian A:|\
sash V:|\
sassy N:|\
saurian N:|\
scabbard V:|\
scaffold V:|\
scald A:|\
scamp V:|\
scandal V:|\
scenic N:|\
scepter V:|\
sceptre V:|\
schmooze N:|\
scholastic N:|\
schoolmaster V:|\
sciatic N:|\
sconce V:|\
scoot N:|\
scour N:|\
scow V:|\
scrag V:|\
scribe V:|\
scrooge V:|\
sear A:|\
sector V:|\
secular N:|\
sediment V:|\
seeming N:|\
seep N:|\
seethe N:|\
self V:|\
semiotic N:|\
semisolid N:|\
send N:|\
senile N:|\
sentient N:|\
sentinel V:|\
sere N:|\
serge V:|\
serpentine V:|\
serrate V:|\
servo V:|\
sewer V:|\
shack V:|\
shallow V:|\
shammy V:|\
shank V:|\
shanty V:|\
sheaf V:|\
sheave V:|\
sheen A:|\
sheen V:|\
sheeny N:|\
sheet V:|\
shelf V:|\
shier N:|\
shinny N:|\
shirk N:|\
shoal A:|\
shook N:|\
shore A:|\
shortwave V:|\
shorty A:|\
shot V:|\
shrimp A:|\
shrine V:|\
shut N:|\
sickly V:|\
siege V:|\
signet V:|\
significant N:|\
signore N:|\
silk V:|\
silkscreen A:|\
silo V:|\
silvan N:|\
simple N:|\
sinew V:|\
sirup V:|\
situate A:|\
skill V:|\
skoal V:|\
skulk N:|\
skyline V:|\
slag V:|\
slang V:|\
slat V:|\
sleeve V:|\
sleuth V:|\
slime V:|\
slink N:|\
slipcover V:|\
slipper V:|\
slipstream V:|\
slosh N:|\
slurry V:|\
slush V:|\
smith V:|\
smooth N:|\
smut V:|\
snafu A:|\
snafu V:|\
snapshot V:|\
snood V:|\
snoot V:|\
soaring N:|\
socket V:|\
sodden V:|\
soft N:|\
softbound N:|\
solar N:|\
sonnet V:|\
soot V:|\
sooth A:|\
sophomore A:|\
sorry N:|\
sourdough A:|\
south V:|\
southeastward N:|\
southwestward N:|\
spec A:|\
spelt N:|\
sphere V:|\
spiderweb V:|\
spire V:|\
splayfoot A:|\
splenetic N:|\
spoke V:|\
spouse V:|\
sprig V:|\
spud V:|\
spurn N:|\
squab A:|\
squadron V:|\
squander N:|\
squib V:|\
stadia N:|\
stag V:|\
stanch N:|\
stanchion V:|\
starboard V:|\
startle N:|\
stationary N:|\
statue V:|\
staunch N:|\
stead V:|\
steamer V:|\
steeplechase V:|\
stereo V:|\
stevedore V:|\
sticker V:|\
stifle N:|\
stigmatic N:|\
stiletto V:|\
stilt V:|\
stimulative N:|\
stooge V:|\
stool V:|\
story V:|\
stove V:|straightjacket V:|straightforward N\?:|strait A:|\
strata N:|streamline N:|stretcher V:|stun N:|sturdy N:|\
sty V:|subculture V:|sublimate N:|submarine V:|subnormal N:|\
substantial N:|subteen A:|subterranean N:|subway V:|sudden N:|\
suds V:|suede V:|suicide V:|sulfate V:|sulfur V:|sully N:|summit V:|\
sunburst A:|sundown V:|sunrise A:|superhuman N:|supine N:|supper V:|\
supple V:|supplemental N:|supplementary N:|supreme N:|surname V:|\
surrogate V:|surround N:|suspicion V:|swaddle N:|swan V:|\
sward V:|swinging N:|switchback V:|syllabic N:|syllable V:|syllogistic N:|\
sylvan N:|symbol V:|synapse V:|syrup V:|tabby V:|tabernacle V:|\
tablet V:|\
tabor V:|\
talc V:|\
tallow V:|\
tamper N:|\
tampon V:|\
tang V:|\
tapestry V:|\
tariff V:|\
tawdry N:|\
taxable N:|\
teach N:|\
teasel V:|\
teetotal V:|\
telegram V:|\
telemeter V:|\
tell N:|\
tempest V:|\
temporal N:|\
tenon V:|\
tension V:|\
tertiary N:|\
texture V:|\
theatrical N:|\
theme V:|\
therapeutic N:|\
thermostat V:|\
thickset N:|\
think N:|\
thole V:|\
thorn V:|\
thou V:|\
threat V:|\
throat V:|\
throne V:|\
thumbtack V:|\
thundering N:|\
ticktock V:|\
tier V:|\
tightrope V:|\
tiller V:|\
timber V:|\
tissue V:|\
titular N:|\
toenail V:|\
token V:|\
tole V:|\
tom V:|\
tomcat V:|\
tooth V:|\
tootle N:|\
topsoil V:|\
tore N:|\
torpid N:|\
torrent A:|\
tourney V:|\
tousle N:|\
toward A:|\
toxic N:|\
trance V:|\
transcendent N:|\
transcendental N:|\
tress V:|\
triage V:|\
trice V:|\
trifling N:|\
trig V:|\
trinket V:|\
trochaic N:|\
trolley V:|\
trolly V:|\
truce V:|\
truncheon V:|\
trustee V:|\
tub V:|\
tubercular N:|\
tun V:|\
turpentine V:|\
turtle V:|\
tusk V:|\
tutelary N:|\
twill V:|\
tyre V:|\
ugh N:|\
umber V:|\
umbilical N:|\
umlaut V:|\
underage N:|\
underbid N:|\
underlay V:|\
underwater N:|\
undress A:|\
unemployable N:|\
unessential N:|\
unicycle V:|\
unique N:|\
unite N:|\
unmarried N:|\
unpredictable N:|\
unprofessional N:|\
unquiet N:|\
unsteady V:|\
unthinkable N:|\
untidy V:|\
unwashed N:|\
unworkable N:|\
unworthy N:|\
uppercase V:|\
upright V:|\
upscale V:|\
upstage N:|\
upswing V:|\
urinary N:|\
valiant N:|\
vanish N:|\
vapor V:|\
vapour V:|\
venom V:|\
vermilion V:|\
vesiculate V:|\
vestibule V:|\
via N:|\
vial V:|\
vibrant N:|\
vinegar V:|\
vintage V:|\
viscose A:|\
visor V:|\
vitriol V:|\
vizor V:|\
vocable A:|\
volatile N:|\
volute A:|\
votary A:|\
vouch N:|\
voucher V:|\
vowel V:|\
vulgar N:|\
wafer V:|\
waggon V:|\
wagon V:|\
waiter V:|\
waitress V:|\
wan V:|\
wander N:|\
wardrobe V:|\
ware A:|\
ware V:|\
warm N:|\
watchdog V:|\
wattle A:|\
wavy N:|\
weapon V:|\
wearable N:|\
week A:|\
weeny N:|\
weird N:|\
wench V:|\
westward N:|\
wham A:|\
wharf V:|\
wheelbarrow V:|\
whereas N:|\
wherewith N:|\
wherry V:|\
whet N:|\
whew N:|\
whiplash V:|\
whist A:|\
whist V:|\
white V:|\
whittle N:|\
whore V:|\
wick V:|\
wide N:|\
wife V:|\
willow V:|\
windlass V:|\
window V:|\
windrow V:|\
winnow N:|\
wireless V:|\
wise V:|\
wisp V:|\
without N:|\
witting N:|\
wizard A:|\
woman V:|\
won V:|\
wont V:|\
woodshed V:|\
workday A:|\
worth V:|\
wrack V:|\
wrath A:|\
wreath V:|\
yard V:|\
yarn V:|\
yawl V:|\
yearling A:|\
yeast V:|\
yen V:|\
yore A:|\
yummy N:|\
zest V:|\
zillion A:|\
on N:|rockies N:|known N:|as A:|albert[ \t]N|i A:|her A:|allies[\t]N|then N:|donuts N\?:|us N:|\
less N:|more N:|toward N\?:|anyhow A:|again A:|nope A:|\
forth A:|askance A:|aloud A:|aloft A:|\
afresh A:|all A:|quite A:|hence A:|ergo A:|almost A:|although A:|then A:|\
thereof A:|most A:|too A:|therein A:|out A:|indeed A:|whereof A:|\
in A:|twice A:|viva A:|not A:|often A:|once A:|never A:|nowhere A:|\
where A:|wherein A:|t A:|ago A:|atop A:|notwithstanding A:|\
away A:|very A:|daily A:|why A:|yet A:|since A:|after A:|before A:|\
about A:|brother A:|sister A:|\
feces N:|axes\tN|bases\tN|phenomena[ \t]N[:]*|automata\tN|cherubim[ \t]N[:]*|\
apices\tN|cervices\tN|indices\tN|matrices\tN|vortices\tN|\
elves\tN|halves\tN|hooves\tN|knives\tN|leaves\tN|lives\tN|loaves\tN|\
scarves\tN|selves\tN|sheaves\tN|shelves\tN|wives\tN|wolves\tN|geese\tN|\
lice\tN|mice\tN|children\tN|corpora[ \t]N[:]*|genera\tN|foci\tN|fungi\tN|\
nuclei\tN|radii\tN|stimuli\tN|syllabi\tN|bacteria[ \t]N[:]*|data\tN|errata[ \t]N[:]*|\
media[ \t]N[:]*|memoranda[ \t]N[:]*|ova\tN|strata[ \t]N[:]*|oxen[ \t]N[:]*|calves\tN|feet\tN|\
women\tN|men\tN|well A:|who[ \t]N[:]*|an A:|an[ \t]DCN|themselves N:|\
a[ \t]DNVP|He[ \t]N[:]*|me[ \t]N[:]*|he[ \t]N[:]*|I[ \t]N[:]*|this[ \t]N[:]*|\
that[ \t][AN][:]*|such[ \t]N[:]*|his[ \t]N[:]*|t[ \t]N[:]*|she[ \t]N[:]*|\
you[ \t]N[:]*|we[ \t]N[:]*|they[ \t]N[:]*|them[ \t]N[:]*|him[ \t]N[:]*|\
her[ \t]N[:]*|your[ \t][NA][:]*|my[ \t]N[:]*|herself[ \t]N[:]*|\
himself[ \t]N[:]*|it[ \t]N[:]*|itself[ \t]N[:]*|myself[ \t]N[:]*|\
oneself[ \t]N[:]*|our[ \t]N[:]*|our[ \t]A[:]*|their[ \t]|\
yourself[ \t]N[:]*|ourself[ \t]N[:]*|another[ \t]N[:]*|and[ \t]N[:]*|\
any[ \t]A[:]*|all[ \t]A[:]*|an[ \t]N[:]*|each[ \t]A[:]*|either[ \t]A[:]*|\
every[ \t]A[:]*|half[ \t]A[:]*|many[ \t]N[:]*|many[ \t]A[:]*|\
much[ \t]N[:]*|neither[ \t]A[:]*|no[ \t]A[:]*|some[ \t]N[:]*|\
some[ \t]A[:]*|such[ \t]A[:]*|those[ \t]N[:]*|those[ \t]A[:]*|\
these[ \t]N[:]*|those[ \t]A[:]*|and[ \t]N\?[:]*|within[ \t]|this[ \t]A[:]*|\
into[ \t]N[:]*|what[ \t][NA][:]*|whom[ \t][NA][:]*|whose[ \t][NA][:]*|\
which[ \t]N[:]*|which[ \t]A[:]*|there[ \t]|will[ \t]V[:]*|\
can[ \t]V[:]*|may[ \t]V[:]*|shall[ \t]V[:]*|ought[ \t]V[:]*|must[ \t]V[:]*|\
could[ \t]V[:]*|would[ \t]V[:]*|inter[ \t]A[:]*|school[ \t]A[:]*|\
the[ \t]A[:]*|mod[ \t]A:)/ && !/'/