#!/bin/bash

# This script creates classpath and starts LT server

# Source shell variables for command-line tool
. /etc/languagetool/lt.conf

# Check if LT_JAVA_HOME was set
if [ -z ${LT_JAVA_HOME} ]; then
	echo "Environment variable LT_JAVA_HOME, pointing to Java 8+ executable, must be set."
	exit 1
fi

function create_lt_class_path() {
	LT_CP=${LT_HOME}/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/standalone/*
}

create_lt_class_path

${LT_JAVA_HOME}/bin/java -cp ${LT_CP} org.languagetool.commandline.Main $*
