#!/bin/bash

# This script creates classpath and starts LT server

# Source shell variables for server
. /etc/languagetool/lt.conf

# Check if LT_JAVA_HOME was set
if [ -z ${LT_JAVA_HOME} ]; then
	echo "Environment variable LT_JAVA_HOME, pointing to Java 8+ executable, must be set."
	exit 1
fi

function create_lt_class_path() {
	LT_CP=${LT_HOME}/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/standalone/*
}

#
# Init script for a Java application
#
 
# Check the application status
#
# This function checks if the application is running

check_status() {
  
  if [ ! -f ${LT_PID_FILE} ]; then
  	# No PID file, assume server is not running
  	echo 0
  else
  	# PID file exists, take pid from there
  	LT_PID=`cat ${LT_PID_FILE}`
  	# Check if such process still exists, or process died
  	RUNNING_PID=`ps -q ${LT_PID} -o pid= | tr -d [:space:]`
  	if [ "${LT_PID}" == "${RUNNING_PID}" ]; then
  		echo ${RUNNING_PID}
  	else
  		echo 0
  	fi
  fi
}

# Create options
function build_lt_options() {
	LT_OPTIONS="${LT_JAVA_OPTS} -cp ${LT_CP}"
	if [ ! -z "${LT_SECURE_SERVER}" -a "${LT_SECURE_SERVER}" -eq 1 ]; then
		LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPSServer"
	else
		LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPServer"
	fi
	LT_OPTIONS="${LT_OPTIONS} --config /etc/languagetool/server.properties"
	LT_OPTIONS="${LT_OPTIONS} --port ${LT_PORT}"
}

# Starts the application
start() {
 
  # At first checks if the application is already started calling the check_status
  # function
  pid=$(check_status)

  if [ $pid -ne 0 ] ; then
    echo "${LT_NAME} is already running (PID ${pid})."
    exit 1
  fi
  
  create_lt_class_path
 
  build_lt_options
  
  # Check what server will be started, secure or insecure
  if [ ! -z "${LT_SECURE_SERVER}" -a "${LT_SECURE_SERVER}" -eq 1 ]; then
    echo -n "Starting HTTPS ${LT_NAME} ... "
  else
    echo -n "Starting HTTP ${LT_NAME} ... "
  fi
 
  # Redirects default and error output to a log file
  ${LT_JAVA_HOME}/bin/java ${LT_OPTIONS} >> ${LT_LOG_FILE} 2>&1 &
  echo $! > ${LT_PID_FILE}
  echo "OK"
}
 
# Stops the application
stop() {
 
  # Like as the start function, checks the application status
  pid=$(check_status)
 
  if [ $pid -eq 0 ] ; then
    echo "${LT_NAME} is already stopped."
    exit 1
  fi
 
  # Kills the application process
  echo -n "Stopping ${LT_NAME} ..."
  kill -15 $pid
  rm -f ${LT_PID_FILE}
  echo "OK"
}
 
# Show the application status
status() {
 
  # The check_status function, again ...
  pid=$(check_status)

  # If the PID was returned means the application is running
  if [ ${pid} -ne 0 ] ; then
    echo "${LT_NAME} is running (PID ${pid})."
  else
    echo "${LT_NAME} is stopped."
  fi
 
}
 
# Main logic, a simple case to call functions
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac
 
exit 0