#!/bin/sh

# This script creates classpath for LT programs and starts LT GUI

# Source shell variables for command-line tool
if [ -f /etc/languagetool/lt.conf ]; then
  # Source LT configuration
  . /etc/languagetool/lt.conf
else
  echo "Unable to source configuration file '/etc/languagetool/lt.conf', aborting ..."
  exit 1
fi

# Check if LT_HOME was set
if [ -z ${LT_HOME} ]; then
	echo "Environment variable LT_HOME, root directory of LT installation, must be set. Aborting ..."
	exit 1
fi

# Check if LT_JAVA_HOME was set
if [ -z ${LT_JAVA_HOME} ]; then
	echo "Environment variable LT_JAVA_HOME, pointing to Java 8+ installation, must be set. Aborting ..."
	exit 1
fi

# Creates LT classpath
function create_lt_class_path() {
	LT_CP=${LT_HOME}/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/*
	LT_CP=${LT_CP}:${LT_HOME}/libs/standalone/*
}

create_lt_class_path

# Determine the command name I was called by
MYNAME=`basename "$0"`
LT_COMMON="${LT_JAVA_HOME}/bin/java ${LT_JAVA_OPTS} -cp ${LT_CP}"

if   [ "$MYNAME" == "ltcmd" ]; then
	${LT_COMMON} org.languagetool.commandline.Main $*
elif [ "$MYNAME" == "ltgui" ]; then
	${LT_COMMON} ${LT_GUI_OPTS} org.languagetool.gui.Main $*
elif [ "$MYNAME" == "ltspldic" ]; then
	${LT_COMMON} org.languagetool.tools.SpellDictionaryBuilder $*
elif [ "$MYNAME" == "ltposdic" ]; then
    ${LT_COMMON} org.languagetool.tools.POSDictionaryBuilder $*
elif [ "$MYNAME" == "ltsyndic" ]; then
    ${LT_COMMON} org.languagetool.tools.SynthDictionaryBuilder $*
elif [ "$MYNAME" == "ltexpdic" ]; then
    ${LT_COMMON} org.languagetool.tools.DictionaryExporter $*
fi
