#!/usr/bin/env bash

# This script contains command for quick POS dictionary and SYNTH_ dictionary generation.
# Shell scripts (or rather, symbolic links to "ltshell") are generated by RPM module.

# Adjust as needed
CORPUS_FILE=/opt/app/s/smd/lt/serbian-corpus.txt
CORPUS_HUNSPELL_FILE=/opt/app/s/smd/lt/hunspell-serbian-corpus.txt

if [ ! -f ${CORPUS_FILE} ]; then
    echo "Serbian word corpus file ${CORPUS_FILE} does not exist, aborting ..."
    exit 1
fi

echo "Generating POS Serbian dictionary ..."
ltposdic -i ${CORPUS_FILE} -info serbian.info -o serbian.dict

echo "Generating SYNTH Serbian dictionary ..."
ltsyndic -i ${CORPUS_FILE} -info serbian_synth.info -o serbian_synth.dict

echo "Generating HunSpell dictionary ..."
ltspldic -i ${CORPUS_HUNSPELL_FILE} -info serbian.info -o hunspell/sr_RS.dict