name: 'Dependency Review'
on:
  pull_request:
    paths-ignore: 
      - '**pom.xml'
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No review required" '